sso_client:
  app_name: magazine_lee
  sso_host: http://test1.huaxing.com/
  client_id: aaefa9b943447002d5c0a46a4e4e21e384c69fba63878a2e2996c58c9a50dd30
  client_secret: 992eafc7bbae18d7cb7fbdde9075201d114736618a940b1d892a33f18865d353

es_host: '10.100.97.86:9200'

smtp:
  server: "smtp.partner.outlook.cn"
  port: 587
  account: "work@huaxing.com"
  bcc: ["jarvisli@huaxing.com"]
  password: "CRit2017"
  domain: "huaxing.com"
  test_group_email:
    - jarvisli@huaxing.com
  ticket_switch: true

smtp_intel:
  server: "smtp.office365.com"

casual_email: ['15611360995@163.com',
               'taoyan@huaxing.com',
               'mgdang@huaxing.com',
               'shanhuiyi@huaxing.com',
               'sallyshi@huaxing.com',
               '278122751@qq.com',
               'fanyilai@huaxing.com',
               'whpang@huaxing.com',
               'linanruan@huaxing.com',
               'cefeng@huaxing.com',
               'wenyagao@huaxing.com',
               'jarvisli@huaxing.com',
               'WenYaGao@huaxing.com']

zombie:
  host: "http://router.canary.huaxing.com:9787"
  #host: "http://localhost:8780"
  app_name: 'magazine_dev_lee'

current_bu_id: 244
